FROM ubuntu:noble

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
      cmake \
      g++-14 \
      gfortran \
      git \
      hdf5-tools \
      meson \
      ninja-build \
      libgtest-dev \
      libboost-dev \
      libclang-dev \
      libeigen3-dev \
      libfftw3-dev \
      libgfortran5 \
      libgmp-dev \
      libgsl-dev \
      libhdf5-dev \
      libmpfr-dev \
      libnfft3-dev \
      libopenblas-dev \
      libopenmpi-dev \
      meson \
      ninja-build \
      python3-dev \
      python3-mako \
      python3-matplotlib \
      python3-mpi4py \
      python3-numpy \
      python3-pytest \
      python3-scipy \
      python3-setuptools \
      python3-skimage \
      python3-tomli \
      \
      apt-utils \
      debhelper \
      dpkg-dev

ENV CC=gcc-14 CXX=g++-14
