properties([
  disableConcurrentBuilds(),
  buildDiscarder(logRotator(numToKeepStr: '10', daysToKeepStr: '30'))
])

def platforms = ["noble", "resolute"]
def packages = [
  "triqs_dftkit",
  "triqs_cthyb",
  "triqs_ctseg",
  "triqs_dft_tools",
  "omegamaxent_interface",
  "triqs_tprf",
  "triqs_maxent",
  "triqs_hubbardI",
  "triqs_hartree_fock",
  "solid_dmft",
  "triqs_Nevanlinna",
  "triqs_modest"
]

catchError {
  stage("base img") {
    buildImages(platforms.collect { platform ->
      [ tag: platform,
        context: 'jenkins',
        dockerfile: "Dockerfile.$platform"
      ]
    }, checkout: true)
  }

  def buildPkg = { pkg ->
    def srcDir = WORKSPACE
    def pkgDir = "$srcDir/$pkg"
    def buildDir = "$WORKSPACE_TMP/build/$pkg"
    def installDir = "$WORKSPACE_TMP/install"
    def args = ""
    if (pkg == "triqs_cthyb") {
      args += " -DMeasureG2=ON"
    }
    dir(buildDir) {
      // packaging requries prefix /usr, but we also want to install; rather than rebuilding install into /usr
      sh """
        cmake $pkgDir -DBUILD_DEBIAN_PACKAGE=1 -DCMAKE_INSTALL_PREFIX=/usr $args
        make -j\$PARALLEL package
        mv $pkg-*.deb $srcDir
        cmake $pkgDir -DBUILD_DEBIAN_PACKAGE=0 -DCMAKE_INSTALL_PREFIX=$installDir $args
        make -j\$PARALLEL install
      """
      dir('test') {
        catchError(buildResult: 'UNSTABLE', stageResult: 'UNSTABLE') {
          sh """
            . $installDir/share/$pkg/${pkg}vars.sh
            cmake $srcDir/test/$pkg
            make -j\$PARALLEL
            OPENBLAS_NUM_THREADS=1 make test CTEST_OUTPUT_ON_FAILURE=1
          """
        }
      }
    }
  }

  stage("triqs pkg") {
    parallel platforms.collectEntries { platform -> [(platform): {
      timeout(time: 2, unit: 'HOURS') {
        runPod(tag: platform) {
          stage("triqs-$platform") {
            def deb = buildPkg("triqs")
            stash name: "$platform-triqs", includes: "triqs-*.deb"
          }
        }
      }
    } ] }
  }
  stage("triqs img") {
    buildImages(platforms.collect { platform ->
      [ tag: "$platform-triqs",
        prep: {
          unstash name: "$platform-triqs"
          def img = imageName(platform)
          writeFile(file: "Dockerfile", text:
"""
FROM $img
COPY triqs-*.deb /tmp
RUN dpkg -i /tmp/triqs-*.deb
""")
        }
      ]
    }, checkout: false)
  }

  parallel platforms.collectEntries { platform -> [(platform): {
    timeout(time: 3, unit: 'HOURS') {
      runPod(tag: "$platform-triqs") {
        stage("$platform pkgs") {
          def repo = "$WORKSPACE_TMP/repo"
          dir (repo) {
            unstash name: "$platform-triqs"
          }
          packages.each { pkg ->
            buildPkg(pkg)
            sh "mv $pkg-*.deb $repo"
          }
          dir(repo) {
            withCredentials([file(credentialsId: 'triqs-packaging-key', variable: 'SECRET')]) {
              sh 'cp $SECRET secret.gpg'
            }
            sh """
              cp $WORKSPACE/public.gpg .
              gpg --import -v -v secret.gpg public.gpg
              rm secret.gpg
              apt-ftparchive packages . > Packages
              gzip -k Packages && bzip2 -k Packages
              apt-ftparchive release . > release && mv release Release
              gpg --digest-algo SHA512 --clearsign -o InRelease Release
              gpg --digest-algo SHA512 -abs -o Release.gpg Release
              tar czf $WORKSPACE/${platform}.tgz .
            """
          }
          archiveArtifacts(artifacts: "${platform}.tgz")
        }
      }
    }
  } ] }
}
emailFailure()
